from PIL import Image, ImageDraw, ImageFont
'''
myim = Image.open("images/kap_01.png")
mask = Image.open("images/mask.png")
print("Image size:")
print(myim.size)
print("Mask size:")
print(mask.size)
mask = mask.resize(myim.size)
mask.putalpha(128)
print("Image size After:")
print(myim.size)
print("Mask size After:")
print(mask.size)
myim.paste(mask, (0, 0), mask)
myim.show()
'''
myim2 = Image.open("images/1399350_resized.PNG")
#myim2 = myim2.resize((1399,350))
mymask2 = Image.open("images/Link-PMP-Badge.png")
mymask2 = mymask2.resize((300,300))
myim2.paste(mymask2, (1099, 50), mymask2)
myim2.show()
myim2.save("images/1399350_linkedin.PNG")